kind: Service
apiVersion: v1
metadata:
  name: service
  namespace: flask-api-ns
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort
